name: Build and Deploy to Azure

env:
  AZURE_CONTAINER_REGISTRY_NAME: "BYD1370"
  AZURE_CONTAINER_REGISTRY: "byd1370.azurecr.io"
  CONTAINER_NAME: "hello-world"
  RESOURCE_GROUP: "1"
  CLUSTER_NAME: "BYD1370"

on:
  push: 
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  buildContainerImage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1

      - name: Set up Docker Builx
        uses: docker/setup-buildx-action@v3.7.1

      - name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:
           # Container registry username
           username: ${{ env.AZURE_CONTAINER_REGISTRY_NAME }}
           # Container registry password
           password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}
           # Container registry server url
           login-server: ${{ env.AZURE_CONTAINER_REGISTRY }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v6.9.0
        with:
           push: true
           tags: ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.CONTAINER_NAME }}:${{ github.sha }}
           file: ./Dockerfile
          
  deployToAKS:
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      id-token: write

    environment: Production

    needs: [buildContainerImage]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1

      - name: Azure Login
        uses: Azure/login@v2.2.0
        with:
          client-id: 'ea257379-199b-431a-b868-f5bfee2fefb2'
          tenant-id: 'c940217c-60d9-4d61-b44c-d8f8a70feb10'
          subscription-id: 'd3415582-e4fb-4727-9794-1b409fd5f57c'

      - name: Setup kubelogin
        uses: Azure/use-kubelogin@v1
        with:
          kubelogin-version: 'v0.0.25'

      - name: Get K8s Context
        uses: Azure/aks-set-context@v3
        with:
          resource-group: ${{ env.RESOURCE_GROUP }}
          cluster-name: ${{ env.CLUSTER_NAME }}
          admin: 'false'
          use-kubelogin: 'true'

      - name: envsubst-action
        uses: danielr1996/envsubst-action@1.1.0
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          AZURE_CONTAINER_REGISTRY: ${{ env.AZURE_CONTAINER_REGISTRY }}
          CONTAINER_NAME: ${{ env.CONTAINER_NAME }}
        with:
          input:
            kubernetes/hello-world-deployment.yaml
          output:
            hello-world-deployment.yaml

      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v4.9
        with:
          action: deploy
          manifests: |
            hello-world-deployment.yaml
            kubernetes/hello-world-service.yaml
          images: ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.CONTAINER_NAME }}:${{ github.sha }}
